# Generated by Django 3.2.5 on 2021-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210731_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='idno',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
