# Generated by Django 3.2.5 on 2021-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_idno'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
