# Generated by Django 3.2.5 on 2021-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='box',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='county',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='town',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
