# Generated by Django 3.2.5 on 2021-07-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210731_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='town',
        ),
    ]
