# Generated by Django 3.2.5 on 2021-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210731_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='town',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
