# Generated by Django 3.2.5 on 2021-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210731_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=120, null=True)),
                ('idno', models.IntegerField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('jobtype', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
