# Generated by Django 3.2.5 on 2021-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_jobrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='idno',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
