# Generated by Django 3.2.5 on 2021-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
