# Generated by Django 3.2.5 on 2021-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='datecompleted',
            field=models.DateField(null=True),
        ),
    ]
