# Generated by Django 3.2.5 on 2021-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_jobrequest_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateposted',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
