# Generated by Django 3.2.5 on 2021-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20211201_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kradata',
            name='datesend',
        ),
        migrations.AddField(
            model_name='kradata',
            name='dateposted',
            field=models.DateTimeField(null=True),
        ),
    ]
