# Generated by Django 3.2.5 on 2021-12-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20211201_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kradata',
            old_name='dateposted',
            new_name='datesend',
        ),
    ]
