# Generated by Django 3.2.5 on 2021-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_remove_krarecords_mobile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='krarecords',
            name='datecompleted',
            field=models.DateField(null=True),
        ),
    ]
