# Generated by Django 3.2.5 on 2021-12-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_krarecords_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=120, null=True)),
                ('yourpin', models.CharField(max_length=120, null=True)),
                ('employerpin', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('p9form', models.ImageField(blank=True, null=True, upload_to='images')),
                ('datesend', models.DateTimeField(null=True)),
                ('datecompleted', models.DateField(null=True)),
            ],
        ),
    ]
