# Generated by Django 3.2.5 on 2021-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='datesend',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='datesend',
            field=models.DateField(null=True),
        ),
    ]
