# Generated by Django 3.2.5 on 2021-12-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_auto_20211224_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
